package com.nigealm.agent.impl;

/**
 * Created by Gil on 12/02/2016.
 * Class to hold Mongo constants
 */
public interface MongoDBConstants {
    // Tool names
    String MONGODB_CONFIGURATION_TOOL_NAME_JENKINS = "jenkins";
    String MONGODB_CONFIGURATION_TOOL_NAME_BAMBOO = "bamboo";
    String MONGODB_CONFIGURATION_TOOL_NAME_JIRA = "jira";
    String MONGODB_CONFIGURATION_TOOL_NAME_GITHUB = "github";
    String MONGODB_CONFIGURATION_TOOL_NAME_GITLAB = "gitlab";
    String MONGODB_CONFIGURATION_TOOL_NAME_BITBUCKET = "bitbucket";
    // Jenkins
    String MONGODB_CONFIGURATION_JENKINS_HOSTNAME = "hostName";
    String MONGODB_CONFIGURATION_JENKINS_PORT = "port";
    String MONGODB_CONFIGURATION_JENKINS_PROJECT_NAME = "projectName";
    String MONGODB_CONFIGURATION_JENKINS_USER = "user";
    String MONGODB_CONFIGURATION_JENKINS_PASSWORD = "password";
    // Bamboo
    String MONGODB_CONFIGURATION_BAMBOO_HOSTNAME = "hostname";
    String MONGODB_CONFIGURATION_BAMBOO_PORT = "port";
    String MONGODB_CONFIGURATION_BAMBOO_USER_NAME = "userName";
    String MONGODB_CONFIGURATION_BAMBOO_PASSWORD = "password";
    String MONGODB_CONFIGURATION_BAMBOO_PLAN_KEY = "planKey";
    String MONGODB_CONFIGURATION_BAMBOO_PROJECT_KEY = "projectKey";
    // Jira
    String MONGODB_CONFIGURATION_JIRA_JIRA_SERVER_URI = "jiraServerUri";
    String MONGODB_CONFIGURATION_JIRA_PROJECT_NAME = "projectName";
    String MONGODB_CONFIGURATION_JIRA_USER_NAME = "userName";
    String MONGODB_CONFIGURATION_JIRA_PASSWORD = "password";
    // GitHub
    String MONGODB_CONFIGURATION_GITHUB_USER_NAME = "userName";
    String MONGODB_CONFIGURATION_GITHUB_PASSWORD = "password";
    String MONGODB_CONFIGURATION_GITHUB_TOKEN = "access_token";
    String MONGODB_CONFIGURATION_GITHUB_REPOSITORY_NAME = "repo";
    String MONGODB_CONFIGURATION_GITHUB_VERSION_BRANCH_NAME = "branch";
    // GitLAB
    String MONGODB_CONFIGURATION_GITLAB_SERVER_URL = "serverUrl";
    String MONGODB_CONFIGURATION_GITLAB_TOKEN = "token";
    String MONGODB_CONFIGURATION_GITLAB_PROJECT_NAME = "projectName";
    String MONGODB_CONFIGURATION_GITLAB_BRANCH_NAME = "branchName";

    String MONGODB_CONFIGURATION_BITBUCKET_REFRESH_TOKEN = "refresh_token";
    String MONGODB_CONFIGURATION_BITBUCKET_REPOSITORY_NAME = "repo";
    String MONGODB_CONFIGURATION_BITBUCKET_VERSION_BRANCH_NAME = "branch";

}
